sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 7811

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 1
    access-key-secret: 1
    bucket-name: sky-tcdawang
  redis:
    host: localhost
    port: 6379
    database: 0
